!conda install pytorch torchvision torchaudio -c pytorch

In [1]:
import torch

print(torch.__version__)

2.5.1+cu118


scals (0D 텐서)

In [2]:
import numpy as np
data1 = np.array(10) # 0차원 텐서는 Nimpy로 선언
print(data1, data1.ndim, data1.shape) # ndim은 axis축, shape은 행렬의 차원을 의미한다.

10 0 ()


vector (1D 텐서)

In [5]:
import torch
data1 = torch.FloatTensor([1,2])# 1, 2 원소를 가진 1D텐서 선언
print(data1, data1.dim(), data1.shape)
# tensor([1., 2.]) 1 torch.Size([2])
# torch size는 크기를 의미

data2 = torch.FloatTensor(3) # 임의의 3개의 원소를 가진 1D텐서 선언
print(data2, data2.dim(), data2.shape)
# tensor([0., 0., 0.]) 1 torch.Size([3])
# torch size는 크기를 의미하며 원소가 벡터 원소 3개 -> 사이즈 3

tensor([1., 2.]) 1 torch.Size([2])
tensor([1., 2., 0.]) 1 torch.Size([3])


In [8]:
# matrix (2D 텐서) -> 행렬이라고 많이 부르는거
data3 = torch.FloatTensor(3,2) # shape을 기반으로 임의의 원소값을 가진 텐서 선언
print(data3, data3.dim(), data3.shape)

data4 = torch.FloatTensor([[1, 2],[3, 4],[5, 6]])# 텐서 구조와 원소값을 파이썬 리스트 기반으로 넣어서 해당 텐서 선언
print(data4, data4.dim(), data4.shape) # dim()은 축, shape은 행렬의 차원을 의미한다.

tensor([[-3.2189e+29,  8.4218e-43],
        [ 0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00]]) 2 torch.Size([3, 2])
tensor([[1., 2.],
        [3., 4.],
        [5., 6.]]) 2 torch.Size([3, 2])


In [9]:
# 3D 텐서 (높이, 넓이, 깊이) => (y, x, z) => (행, 열, 깊이)
data5 = torch.FloatTensor(3,2,1) # shape을 기반으로 임의의 원소값을 가진 텐서 선언
print(data5, data5.dim(), data5.shape)

data6 = torch.FloatTensor([ [ [1], [2], ], [ [3], [4] ], [ [5], [6] ] ]) # 밖에서부터 안쪽으로 3개 2개 1개 원소값으로 선언
print(data6, data6.dim(), data6.shape) # dim()은 축, shape은 행렬의 차원을 의미

tensor([[[-3.2191e+29],
         [ 8.4218e-43]],

        [[ 0.0000e+00],
         [ 0.0000e+00]],

        [[ 0.0000e+00],
         [ 0.0000e+00]]]) 3 torch.Size([3, 2, 1])
tensor([[[1.],
         [2.]],

        [[3.],
         [4.]],

        [[5.],
         [6.]]]) 3 torch.Size([3, 2, 1])


In [10]:
# 밖에서부터 안쪽으로 텐서 선언 이해하기
data7 = torch.FloatTensor([ [1], [2], [3] ])
print(data7, data7.dim(), data7.shape)

data8 = torch.FloatTensor([ [1, 2, 3] ])
print(data8, data8.dim(), data8.shape)

tensor([[1.],
        [2.],
        [3.]]) 2 torch.Size([3, 1])
tensor([[1., 2., 3.]]) 2 torch.Size([1, 3])
