## Tensor 생성 주요 메서드
- torch.zeros(x, y, z): 0의 값으로 shape모양의 텐서 생성
- torch.ones(x, y, z): 1값으로 shape 모앵의 텐서 생성
- torch.rand(x, y, z): 0부터 1 사이에 균일한 확률 분포로 랜덤한 값을 가진 (x, y) shape의 텐서 생성
- torch.full((x, y, z), a): a값으로 shape 모양의 텐서 생성
<br><br>
- torch.zeros_like(tensor): 인자로 들어간 tensor 객체와 동일 shape 를 가지되, 각 원소값은 0 으로 이루어진 텐서 생성
- torch.ones_like(tensor): 인자로 들어간 tensor 객체와 동일 shape 를 가지되, 각 원소값은 0 으로 이루어진 텐서 생성
- torch.rand_like(tensor): 0 부터 1 사이에 균일한 확률 분포로 랜덤한 값을 가진 (x, y) shape 의 텐서 생성
- torch.randn_like(tensor): 인자로 들어간 tensor 객체와 동일 shape 를 가지되, 각 원소값은 randn() 의 랜덤값으로 채워진 텐서 생성
- torch.full_like(tensor, a): 인자로 들어간 tensor 객체와 동일 shape 를 가지되, 각 원소값은 a 값으로 이루어진 텐서 생성
<br><br>
- torch.empty(x, y, z): 특정 의도로 초기화 되지 않은 값을 가진 (x, y) shape 의 행렬 생성
> shape 은 여러 차원이 될 수 있음 
> 각 메서드에 dtype=type 인자를 넣어, 데이터 타입 명시 가능

In [1]:
import torch

data1 = torch.zeros(2, dtype=torch.float)
data2 = torch.ones(2, 2, dtype=torch.double)
data3 = torch.rand(2,2,3, dtype=torch.half) # 16비트 float을 half 라고 함
data4 = torch.randn(2,2,3,4) # 자동으로 float 32 형으로 설정 됨
data5 = torch.full((2,4), 10)

In [2]:
# 형태 확인
print(data1.shape, data2.shape, data3.shape, data4.shape, data5.shape) 

torch.Size([2]) torch.Size([2, 2]) torch.Size([2, 2, 3]) torch.Size([2, 2, 3, 4]) torch.Size([2, 4])


In [3]:
# 배열의 차원을 나타냄
print(data1.ndim, data2.ndim, data3.ndim, data4.ndim, data5.ndim)
print(data1.dim(), data2.dim(), data3.dim(), data4.dim(), data5.dim()) # dim() 메서드로도 차원값 확인 가능하다.

1 2 3 4 2
1 2 3 4 2


In [4]:
# 데이터 타입 확인
print(data1.dtype, data2.dtype, data3.dtype, data4.dtype, data5.dtype)

torch.float32 torch.float64 torch.float16 torch.float32 torch.int64


In [5]:
# 데이터 사이즈(원소의 갯수)확인
# numpy와 다르게 size가 아니라 size() 라는 메서드로 제공된다.
print(data1.size(), data2.size(), data3.size(), data4.size(), data5.size())

torch.Size([2]) torch.Size([2, 2]) torch.Size([2, 2, 3]) torch.Size([2, 2, 3, 4]) torch.Size([2, 4])


In [6]:
# 각 원소값을 직접 대입하여 tensor 선언하기
data6 = torch.FloatTensor([[1,2],[3,4]])
data7 = torch.DoubleTensor([[1,2,3],[4,5,6]])
data8 = torch.LongTensor([[1,2,3],[4,5,6],[7,8,9]])

# shape 기반으로 tensor 선언하기
data9 = torch.FloatTensor(2,3,5)
data10 = torch.DoubleTensor(3,3,2,4)
data11 = torch.LongTensor(4,4)

In [10]:
data11

tensor([[3941924798592,             0,             0,             0],
        [            0,             0,             0,             0],
        [            0,             0,             0,             0],
        [            0,             0,             0,             0]])

In [11]:
# _like()로 tensor생성
data12 = torch.full_like(data5, 20)

In [13]:
# 안의 내용들이 설정된 값(20)으로 바뀐 것을 알 수 있음
print(data5)
print(data12)

tensor([[10, 10, 10, 10],
        [10, 10, 10, 10]])
tensor([[20, 20, 20, 20],
        [20, 20, 20, 20]])


### reshape(): 배열 구조 변경하기

In [14]:
import torch

data1 = torch.DoubleTensor([[1,2,3],[4,5,6]])
print(data1)
data1 = data1.reshape(3,2)
print(data1)
data1 = data1.reshape(2,-1) # -1은 열은 행의 갯수에 맞춰 자동 계산 하도록 하는 것
print(data1)

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)
tensor([[1., 2.],
        [3., 4.],
        [5., 6.]], dtype=torch.float64)
tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)


### view() : 텐서 구조 변경
- pytorch 에서는 numpy 처럼 reshape() 로 배열 구조를 변경할 수 있지만, reshape() 보다 view() 메서드를 보다 많이 사용함
- view() 메서드는 reshape() 와 사용법은 동일

> 원소 수를 유지하면서 텐서의 크기 변경할 때 많이 사용하며, 매우 중요함!

> 상당히 헷깔리므로, 높이, 너비, 깊이 순서로 순서를 기억하는 편이 좋음 -> 나는 행 열 깊이 로 외우는게 편함

<img src="https://www.fun-coding.org/00_Images/tensor-R.png">

In [20]:
import torch

data1 = torch.DoubleTensor([
    [[1,2,3],
    [4,5,6]],
    [[7,8,9],
    [10,11,12]]
])
print(data1.shape, "높이:", data1.size(0), "너비:", data1.size(1), "깊이:", data1.size(2))

torch.Size([2, 2, 3]) 높이: 2 너비: 2 깊이: 3


In [22]:
# view 를 통해서 바꾸는 모습, 
data1 = data1.view(2,-1)
print(data1, data1.shape)

data1 = data1.view(-1, 3)
print(data1, data1.shape)

data1 = data1.view(3,2,-1)
print(data1, data1.shape)

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.],
        [ 7.,  8.,  9., 10., 11., 12.]], dtype=torch.float64) torch.Size([2, 6])
tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]], dtype=torch.float64) torch.Size([4, 3])
tensor([[[ 1.,  2.],
         [ 3.,  4.]],

        [[ 5.,  6.],
         [ 7.,  8.]],

        [[ 9., 10.],
         [11., 12.]]], dtype=torch.float64) torch.Size([3, 2, 2])


### squeeze() : 텐서 차원 압축
- 차원이 1인 경우, 해당 차원을 제거

In [23]:
data1 = torch.FloatTensor([[1],[2],[3]])
data2 = data1.squeeze()
print(data1, data1.dim(), data1.shape)
print(data2, data2.dim(), data2.shape)

tensor([[1.],
        [2.],
        [3.]]) 2 torch.Size([3, 1])
tensor([1., 2., 3.]) 1 torch.Size([3])


 ### unsqueeze() : 특정 위치에 1인 차원을 추가

In [24]:
data1 = torch.FloatTensor([ [1,2,3], [4,5,6]])
print(data1, data1.dim(), data1.shape)

tensor([[1., 2., 3.],
        [4., 5., 6.]]) 2 torch.Size([2, 3])


In [27]:
# 원하는 위치에 1인 차원을 추가하고 나머지는 뒤로 밀리는 구조
data2 = data1.unsqueeze(0)
data3 = data1.unsqueeze(2)
print(data2, data2.dim(), data2.shape)
print(data3, data3.dim(), data3.shape)

tensor([[[1., 2., 3.],
         [4., 5., 6.]]]) 3 torch.Size([1, 2, 3])
tensor([[[1.],
         [2.],
         [3.]],

        [[4.],
         [5.],
         [6.]]]) 3 torch.Size([2, 3, 1])
