In [1]:
import numpy as np

In [2]:
data1 = np.array([[1,2,3],[4,5,6]])
data2 = np.array([[1,2,3],[4,5,6]])

In [3]:
# 넘파이 계산
data1 + data2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [4]:
data1 - data2

array([[0, 0, 0],
       [0, 0, 0]])

In [5]:
data1 * data2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [6]:
data1 / data2

array([[1., 1., 1.],
       [1., 1., 1.]])

In [7]:
data1 % data2

array([[0, 0, 0],
       [0, 0, 0]])

In [8]:
data1 // data2

array([[1, 1, 1],
       [1, 1, 1]])

In [10]:
data1 + 1

array([[2, 3, 4],
       [5, 6, 7]])

In [15]:
data2 = np.array([[1,2], [3,4], [5,6]])
data3 = np.array([[1],[2],[3]])
data2 + data3
# 브로드 캐스팅 확

array([[2, 3],
       [5, 6],
       [8, 9]])

In [18]:
# 넘파이 행렬 곱셈은 @로 계산
data1 @ np.transpose(data1)

array([[14, 32],
       [32, 77]])

In [24]:
data1[[0, 1]] # 행 선택
data1[[1]][:,2] # 1행 2열 선택

array([6])

In [27]:
# 넘파이의 복사
# 얕은 복사 -> 슬라이싱 
# 깊은 복사 -> 슬라이싱.copy()
deep_data = data1[[1]][:,1].copy()
deep_data

array([5])

In [30]:
# 넘파이의 where
# 조건에 맞는 인덱스 번호를 리턴한다.
idx = np.where(data1 > 3) # 인덱스 추출해줌
data1[idx]

array([4, 5, 6])

In [31]:
np.where(data1>3, 1, -1)

array([[-1, -1, -1],
       [ 1,  1,  1]])

In [32]:
# 넘파이 저장 방법
# np.save('이름', data1) 이렇게 하면 저장이 가능
# 읽어오기
# np.load('이름(경로)')

In [ ]:
# 여러개의 넘파이를 하나로 저장하는 경우
# np.savez('이름', five=data1, ten=data2, hundred=data3)
# 위의 five ten... 이것들은 임의로 정한 이름들, 다른거 써도 됨
# 나중에 데이터 불러와서 data['five'] 이런식으로 확인 가능


In [ ]:
# 3차원 텐서는 k n m 으로 표기 (높이, 행, 열)