In [1]:
# 선형대수 과목에서 익힘 -> 텐서에 사용

torch.matmul() 메서드는 2D텐서 3D텐서간의 연산만 지원, 일반 matmul()과의 차이점을 알아둘 필요 있음 <br>
matmul()은 텐서의 shape등에 따라, 다양한 계산이 가능, broadcasting도 지원하므로, 자칫 예상치못한 연산이 될 수도 있다. <br>
디버깅을 위해, 기대한 케이스에 대해서만 명확한 계산을 하는 것이 필요하다면, torch.mm(), torch.bmm() 사용을 고려해야 함

In [2]:
import torch

In [3]:
A = torch.full((3,), 2) # 벡터 생성
B = torch.full((3,), 3) # 벡터 생성

In [9]:
print(A, A.dim(), A.shape)
print(B, B.dim(), B.shape)
result = torch.matmul(A,B) # 1차원 텐서의 곱, 각 요소들 곱하고 더하기
print(result, result.shape)

tensor([2, 2, 2]) 1 torch.Size([3])
tensor([3, 3, 3]) 1 torch.Size([3])
tensor(18) torch.Size([])


In [11]:
# 2차원 텐서의 곱 = 행렬 곱
A = torch.full((2,3), 2)
B = torch.full((3,3), 3)
result = torch.matmul(A,B)
print(result)

tensor([[18, 18, 18],
        [18, 18, 18]])


In [19]:
# 벡터 X 행열 -> 벡터를 matrix에 맞게 transpose 해준다. (matmul에서 자동으로 해줌)
A = torch.full((3,), 2)
B = torch.full((3,2), 3)
result = torch.matmul(A, B)
print(result) # 결과로 벡터가 나옴 1 x 2 형태 행 벡터
print(result.size())
print(result.ndim)

tensor([18, 18])
torch.Size([2])
1


In [25]:
# 벡터 x 3차원 이상의 텐서 => 뭘까
# (a) x (b,c,d) 형태에서 (b,c,d) = b x (c, d)
# = (b) x ((a) x (c, d)) => (b) x (d) => (b, d)
A = torch.full((3,), 2)
B = torch.full((4,3,2),3)
result = torch.matmul(A, B)
print(result)
print(result.shape)

tensor([[18, 18],
        [18, 18],
        [18, 18],
        [18, 18]])
torch.Size([4, 2])


In [27]:
# 곱셈의 순서도 중요한데 
# 행렬 x 벡터 의 경우 위에서 배운 벡터x행렬과는 거의 비슷
A = torch.full((3,2), 3)
B = torch.full((2,), 2)
result = torch.matmul(A, B)
print(result)
print(result.shape)# (3, 2) x (2, 1) => 3, 1 => (3) 이렇게 된다. (거의 비슷)

tensor([12, 12, 12])
torch.Size([3])


In [28]:
# 3차원 이상의 텐서
A = torch.full((4,3,2), 3)
B = torch.full((2,), 2)
result = torch.matmul(A, B)
print(result)
print(result.shape)

tensor([[12, 12, 12],
        [12, 12, 12],
        [12, 12, 12],
        [12, 12, 12]])
torch.Size([4, 3])


In [ ]:
# 3차원텐서 x 벡터 (설)
# (a,b,c) x (d)
# a x (b, c) x (d) => 여기서 c와 d가 같아야 계산이 성립함
# a x (b, c) x (c,) = a x (b) = (a, b) 이렇게 됨

In [ ]:
# torch.mm 행렬 곱만 지원
# torch.bmm 3d 텐서 끼리 곱만 지원
# 위의 두 개는 브로드캐스팅같은거 지원 x 
# 장점: 원하지 않는 곱 안해줌
# 단점: static하게만 사용 가능

In [1]:
import torch

In [2]:
x = torch.FloatTensor(4) # 입력
w = torch.FloatTensor(4,3) # 가중치
b = torch.FloatTensor(3) # 편향

In [3]:
def linearfunction(x,w,b):
    y = torch.matmul(x,w) + b
    return y

In [4]:
y = linearfunction(x,w,b)
print(y)
print(y.shape)

tensor([3.8870e+10, 2.7615e-37, 0.0000e+00])
torch.Size([3])


In [7]:
# 신경망 모델 클래스를 만들고, nn.Module 을 상속받는다.
# __init__ 에서 신경망 계층 초기화를 선언한다.
# forward() 메서드에서 입력 데이터에 대한 연산을 정의한다.

In [5]:
import torch
import torch.nn as nn

In [6]:
class NeuralNetwork(nn.Module):
    def __init__(self):
        super().__init__()
        self.w = torch.FloatTensor(4, 3) # 입력차원과 출력차원을 써줘야함
        self.b = torch.FloatTensor(3) # 편향, 출력차원 수 만큼 필요함
    def forward(self, x):
        y = torch.matmul(x, self.w) + self.b
        return y

In [8]:
x = torch.FloatTensor(4)
mylinear = NeuralNetwork()
y = mylinear(x) # .forward 를 안써도 알아서 forward로 호출해서 사용

In [9]:
print(y.shape)

torch.Size([3])


In [11]:
# 연습
import torch
import torch.nn

class NeuralNetwork(nn.Module): # 상속받는거임
    def __init__(self, input_dim, output_dim):
        super().__init__()
        self.w = torch.FloatTensor(input_dim, output_dim)
        self.b = torch.FloatTensor(output_dim)

    def forward(self, x): # 오버라이딩 하는거
        y = torch.matmul(x, self.w) + self.b
        return y

In [14]:
# 실행 연습
x = torch.FloatTensor(5)
mylinear = NeuralNetwork(5,3)
y = mylinear(x)
print(y)
print(y.shape)

tensor([1.9673e+05, 1.4041e-42, 0.0000e+00])
torch.Size([3])


In [17]:
# 위의 것보다 파라미터 정하는 것을 실전에 가깝게 만든거
import torch
import torch.nn as nn

class NeuralNetwork(nn.Module): # 상속받는거임
    def __init__(self, input_dim, output_dim):
        super().__init__()
        self.w = nn.Parameter(torch.FloatTensor(input_dim, output_dim)) # 변수가 파라미터로 등록되게 하는 것
        self.b = nn.Parameter(torch.FloatTensor(output_dim))

    def forward(self, x): # 오버라이딩 하는거
        y = torch.matmul(x, self.w) + self.b
        return y

In [25]:
x = torch.FloatTensor(4)
mylinear = NeuralNetwork(4,3)
y = mylinear(x)
print(y)
print(y.shape)
print("------"*10)
for param in mylinear.parameters():
    print(param)
# requires_grad=True : 파라미터 업데이트 설정 on

tensor([0.0000, 2.2798, 0.0000], grad_fn=<AddBackward0>)
torch.Size([3])
------------------------------------------------------------
Parameter containing:
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], requires_grad=True)
Parameter containing:
tensor([0.0000, 2.2798, 0.0000], requires_grad=True)


In [27]:
# y = torch.matmul(x, self.w) + self.b 
# 위에 식 자주 써서 그런지 모듈로 만들어져 있음
# nn.Linear 클래스

mylinear = nn.Linear(4,3)
y = mylinear(x)
print(y)
print(y.shape)

for param in mylinear.parameters():
    print(param)

# 실제 파이토치 모델은 여러가지 최적화, 설정 때문에 클래스로 오버라이딩 하는 경우가 흔하다.

tensor([ 11788.3379,  90582.8281, -24404.5332], grad_fn=<ViewBackward0>)
torch.Size([3])
Parameter containing:
tensor([[ 0.0587, -0.3503, -0.3891, -0.2417],
        [ 0.4513, -0.4304, -0.0329, -0.0826],
        [-0.1216, -0.4168,  0.4741, -0.1038]], requires_grad=True)
Parameter containing:
tensor([ 0.3479, -0.4481, -0.4123], requires_grad=True)


In [ ]:
# 옵티마이저(Optimizer) 
# 손실값을 적게 만들기 위해 사용하는 알고리즘
# GD, BGD, SGD 등등 있음 

In [28]:
# BGD 문제점: 안정적으로 출력을 뽑으나 global minimum이 아닌 local minimum을 찾는 경향이 있음
# SGD : 전체중 랜덤한 데이터를 뽑아서 업데이트를 가져감
# mini batch gradient descent와 비슷

In [1]:
# 오차 역전파 : 편미분, chain rule을 이용한 것
# 조건
# requires_grad = True & (backward() 호출)
# requires_grad = True 이걸로 계산을 추적함 => chain rule을 위함

In [30]:
import torch
x = torch.rand(1, requires_grad = True)
y = torch.rand(1)
y.requires_grad = True
loss = y - x

In [29]:
print(x)
print(y)
print(loss)
print(loss.backward())
print(x.grad, y.grad)

tensor([0.5418], requires_grad=True)
tensor([0.8156], requires_grad=True)
tensor([0.2738], grad_fn=<SubBackward0>)
None
tensor([-1.]) tensor([1.])


In [31]:
x = torch.ones(4)
y = torch.zeros(3)
w = torch.rand(4,3, requires_grad = True)
b = torch.rand(3, requires_grad = True)
z = torch.matmul(x,w) + b
print(w)
print(b)
print(z)

tensor([[0.5185, 0.0203, 0.1158],
        [0.8933, 0.5116, 0.0357],
        [0.6309, 0.1844, 0.7182],
        [0.2833, 0.1977, 0.5367]], requires_grad=True)
tensor([0.0085, 0.9787, 0.7700], requires_grad=True)
tensor([2.3346, 1.8927, 2.1765], grad_fn=<AddBackward0>)


In [33]:
# MSE 사용법 ( torch.nn.function )
import torch.nn.functional as F

loss = F.mse_loss(z, y)
loss.backward()
print(w.grad, b.grad)
print(loss)

tensor([[1.5564, 1.2618, 1.4510],
        [1.5564, 1.2618, 1.4510],
        [1.5564, 1.2618, 1.4510],
        [1.5564, 1.2618, 1.4510]]) tensor([1.5564, 1.2618, 1.4510])
tensor(4.5898, grad_fn=<MseLossBackward0>)


In [34]:
# 파라미터 업데이트 방법
learning_rate = 0.1
threshold = 0.1 # loss가 0.1보다 낮아지면 멈추기
iteration_num = 0

while loss > threshold: # loss가 0.1보다 낮아지면 멈추기
    iteration_num += 1
    w = w - learning_rate * w.grad
    b = b - learning_rate * b.grad
    print(iteration_num, loss, z, y)
    
    w.detach_().requires_grad_(True) # 기존 연산에서 끊어줘야 함, 안하면 1회차 때 연산이 2회차때 2회차때는 3회차때 ... 관여함
    b.detach_().requires_grad_(True) # detach_().requires_grad_(True)가 연산을 끊는 역할을 함 -> chain rule 중간에 끊는 역할    
    z = torch.matmul(x,w) + b
    loss = F.mse_loss(z, y)
    loss.backward()

print(iteration_num + 1, loss, z, y)

1 tensor(4.5898, grad_fn=<MseLossBackward0>) tensor([2.3346, 1.8927, 2.1765], grad_fn=<AddBackward0>) tensor([0., 0., 0.])
2 tensor(2.0399, grad_fn=<MseLossBackward0>) tensor([1.5564, 1.2618, 1.4510], grad_fn=<AddBackward0>) tensor([0., 0., 0.])
3 tensor(0.9066, grad_fn=<MseLossBackward0>) tensor([1.0376, 0.8412, 0.9673], grad_fn=<AddBackward0>) tensor([0., 0., 0.])
4 tensor(0.4029, grad_fn=<MseLossBackward0>) tensor([0.6917, 0.5608, 0.6449], grad_fn=<AddBackward0>) tensor([0., 0., 0.])
5 tensor(0.1791, grad_fn=<MseLossBackward0>) tensor([0.4611, 0.3739, 0.4299], grad_fn=<AddBackward0>) tensor([0., 0., 0.])
6 tensor(0.0796, grad_fn=<MseLossBackward0>) tensor([0.3074, 0.2492, 0.2866], grad_fn=<AddBackward0>) tensor([0., 0., 0.])
