In [1]:
# 선형대수 과목에서 익힘 -> 텐서에 사용

torch.matmul() 메서드는 2D텐서 3D텐서간의 연산만 지원, 일반 matmul()과의 차이점을 알아둘 필요 있음 <br>
matmul()은 텐서의 shape등에 따라, 다양한 계산이 가능, broadcasting도 지원하므로, 자칫 예상치못한 연산이 될 수도 있다. <br>
디버깅을 위해, 기대한 케이스에 대해서만 명확한 계산을 하는 것이 필요하다면, torch.mm(), torch.bmm() 사용을 고려해야 함

In [2]:
import torch

In [3]:
A = torch.full((3,), 2) # 벡터 생성
B = torch.full((3,), 3) # 벡터 생성

In [9]:
print(A, A.dim(), A.shape)
print(B, B.dim(), B.shape)
result = torch.matmul(A,B) # 1차원 텐서의 곱, 각 요소들 곱하고 더하기
print(result, result.shape)

tensor([2, 2, 2]) 1 torch.Size([3])
tensor([3, 3, 3]) 1 torch.Size([3])
tensor(18) torch.Size([])


In [11]:
# 2차원 텐서의 곱 = 행렬 곱
A = torch.full((2,3), 2)
B = torch.full((3,3), 3)
result = torch.matmul(A,B)
print(result)

tensor([[18, 18, 18],
        [18, 18, 18]])


In [19]:
# 벡터 X 행열 -> 벡터를 matrix에 맞게 transpose 해준다. (matmul에서 자동으로 해줌)
A = torch.full((3,), 2)
B = torch.full((3,2), 3)
result = torch.matmul(A, B)
print(result) # 결과로 벡터가 나옴 1 x 2 형태 행 벡터
print(result.size())
print(result.ndim)

tensor([18, 18])
torch.Size([2])
1


In [25]:
# 벡터 x 3차원 이상의 텐서 => 뭘까
# (a) x (b,c,d) 형태에서 (b,c,d) = b x (c, d)
# = (b) x ((a) x (c, d)) => (b) x (d) => (b, d)
A = torch.full((3,), 2)
B = torch.full((4,3,2),3)
result = torch.matmul(A, B)
print(result)
print(result.shape)

tensor([[18, 18],
        [18, 18],
        [18, 18],
        [18, 18]])
torch.Size([4, 2])


In [27]:
# 곱셈의 순서도 중요한데 
# 행렬 x 벡터 의 경우 위에서 배운 벡터x행렬과는 거의 비슷
A = torch.full((3,2), 3)
B = torch.full((2,), 2)
result = torch.matmul(A, B)
print(result)
print(result.shape)# (3, 2) x (2, 1) => 3, 1 => (3) 이렇게 된다. (거의 비슷)

tensor([12, 12, 12])
torch.Size([3])


In [28]:
# 3차원 이상의 텐서
A = torch.full((4,3,2), 3)
B = torch.full((2,), 2)
result = torch.matmul(A, B)
print(result)
print(result.shape)

tensor([[12, 12, 12],
        [12, 12, 12],
        [12, 12, 12],
        [12, 12, 12]])
torch.Size([4, 3])


In [ ]:
# 3차원텐서 x 벡터 (설)
# (a,b,c) x (d)
# a x (b, c) x (d) => 여기서 c와 d가 같아야 계산이 성립함
# a x (b, c) x (c,) = a x (b) = (a, b) 이렇게 됨

In [ ]:
# torch.mm 행렬 곱만 지원
# torch.bmm 3d 텐서 끼리 곱만 지원
# 위의 두 개는 브로드캐스팅같은거 지원 x 
# 장점: 원하지 않는 곱 안해줌
# 단점: static하게만 사용 가능