In [5]:
import torch
import torch.nn as nn

class LinearRegressionModel(nn.Module):
    
    def __init__(self, input_dim, output_dim):
        super().__init__()
        # 명시적으로 인자명을 써주는 경우도 많이 쓰인다고 한다.
        self.linear = nn.Linear(in_features = input_dim, out_features = output_dim)
        self.activation = nn.ReLU() # 시그모이드 함수
        # self.activation = nn.Sigmoid()
    def forward(self, x):
        return self.activation(self.linear(x)) # 리니어 통과 후 활성화 통

In [6]:
x = torch.ones(4) # input
y = torch.zeros(3) # out
model = LinearRegressionModel(4,3)
loss_function = nn.MSELoss()

In [7]:
learning_rate = 0.01
nb_epochs = 1000
optimizer = torch.optim.SGD(model.parameters(), lr = learning_rate)

for epoch in range(nb_epochs + 1):

    y_pred = model(x)
    loss = loss_function(y_pred, y)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()


In [9]:
print(loss) # sigmoid에 비해 relu가 엄청나게 오차를 줄인다. 
for param in model.parameters():
    print(param)

tensor(2.3981e-14, grad_fn=<MseLossBackward0>)
Parameter containing:
tensor([[-0.3151, -0.2600, -0.2867, -0.3219],
        [-0.3371, -0.3982, -0.2403, -0.2803],
        [-0.0550,  0.1615, -0.4580, -0.0344]], requires_grad=True)
Parameter containing:
tensor([-0.4923, -0.3556,  0.3860], requires_grad=True)


## 다층 레이어 구현

In [10]:
import torch
import torch.nn as nn

class LinearRegressionModel(nn.Module):

    def __init__(self,input_dim, output_dim):
        super().__init__()
        self.linear1 = nn.Linear(input_dim, 10)
        self.linear2 = nn.Linear(10, 10)
        self.linear3 = nn.Linear(10, 10)
        self.linear4 = nn.Linear(10, output_dim)
        self.activation = nn.LeakyReLU(0, 1)

    def forward(self, x):
        #|x| = (input_dim, output_dim)
        hidden = self.activation(self.linear1(x))
        hidden = self.activation(self.linear2(hidden))
        hidden = self.activation(self.linear3(hidden))
        y = self.linear4(hidden) # 마지막 출력에는 activation 함수를 사용하지 않는 것이 일반적
        return y # 가시성을 위해 분리해서 쓰는겁니다.

In [11]:
x = torch.ones(4)
y = torch.zeros(3)
model = LinearRegressionModel(4, 3)
loss_function = nn.MSELoss()

In [12]:
learning_rate = 0.01
nb_epochs = 1000
optimizer = torch.optim.SGD(model.parameters(), lr = learning_rate)

for epoch in range(nb_epochs+1):
    y_pred = model(x)
    loss = loss_function(y_pred, y)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

In [13]:
print(loss) # sigmoid에 비해 relu가 엄청나게 오차를 줄인다. 
for param in model.parameters():
    print(param)

tensor(1.1617e-09, grad_fn=<MseLossBackward0>)
Parameter containing:
tensor([[-0.3642, -0.1485, -0.4877,  0.4261],
        [ 0.2456, -0.2232,  0.3042,  0.2432],
        [ 0.2371, -0.2955,  0.0424, -0.3929],
        [ 0.3522, -0.4668,  0.0983,  0.0261],
        [ 0.3196,  0.1378,  0.1978,  0.0635],
        [-0.3038,  0.4129, -0.2057,  0.4990],
        [ 0.2223, -0.4499, -0.1757, -0.2742],
        [ 0.1448, -0.0907, -0.2221,  0.3788],
        [-0.3172, -0.0418,  0.0395,  0.0570],
        [-0.3309, -0.2399,  0.1481,  0.0273]], requires_grad=True)
Parameter containing:
tensor([ 0.4369, -0.3841,  0.0208, -0.0433, -0.4718, -0.4855,  0.2350,  0.1000,
        -0.3320,  0.0508], requires_grad=True)
Parameter containing:
tensor([[ 0.1431,  0.2658, -0.0840,  0.0775,  0.3023, -0.2889, -0.0925, -0.2253,
         -0.1855,  0.2317],
        [-0.2001, -0.1731, -0.1768, -0.1937, -0.2679,  0.0818,  0.0994,  0.2800,
         -0.2285, -0.1274],
        [-0.1450, -0.2877,  0.1533, -0.0866,  0.2098,  0.2822

## nn.Sequential

In [22]:
# 이거 이용하면 더 쉽게 사용 가능하다
x = torch.ones(4)
y = torch.zeros(3)

input_dim = x.size(0)
output_dim = y.size(0)

model = nn.Sequential(
    nn.Linear(input_dim, 10),
    nn.LeakyReLU(0, 1),
    nn.Linear(10, 10),
    nn.LeakyReLU(0, 1),
    nn.Linear(10, 10),
    nn.LeakyReLU(0, 1),
    nn.Linear(10, output_dim)
)

In [24]:
loss_function = nn.MSELoss()
learning_rate = 0.01
nb_epochs = 1000
optimizer = torch.optim.SGD(model.parameters(), lr = learning_rate)

In [25]:
for epoch in range(nb_epochs + 1):

    y_pred = model(x)
    loss = loss_function(y_pred, y)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

In [26]:
print(loss)
for param in model.parameters():
    print(param)

tensor(2.7967e-11, grad_fn=<MseLossBackward0>)
Parameter containing:
tensor([[ 0.1235, -0.0363, -0.2574,  0.3882],
        [-0.3704,  0.2853, -0.0282,  0.4459],
        [ 0.1817,  0.4610,  0.2297, -0.0395],
        [-0.3471, -0.2642,  0.3204, -0.4785],
        [-0.4829, -0.4946, -0.3506, -0.2117],
        [ 0.0484, -0.1762, -0.2569,  0.0910],
        [ 0.4014, -0.2842,  0.0772,  0.2172],
        [-0.0371,  0.1607,  0.2857,  0.4682],
        [-0.0713,  0.4746,  0.4051,  0.3404],
        [ 0.1641,  0.4293, -0.1643, -0.2497]], requires_grad=True)
Parameter containing:
tensor([-0.4962, -0.0631, -0.0854, -0.1095, -0.3312,  0.2602, -0.1722, -0.3223,
         0.1068,  0.2292], requires_grad=True)
Parameter containing:
tensor([[ 0.0130, -0.0036, -0.1720, -0.3079, -0.0130, -0.1700,  0.1768,  0.2610,
          0.0626, -0.1787],
        [-0.1124,  0.2790, -0.1211,  0.1322,  0.2129, -0.2442, -0.0308, -0.0252,
          0.0732, -0.2221],
        [ 0.1126,  0.1695, -0.2334, -0.2124,  0.2976, -0.2676