In [1]:
# ADAM optimizer 테스트

import torch
import torch.nn as nn

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [2]:
x = torch.ones(5000, 10) # 10개의 feature가 있는 5000 개의 데이터
y = torch.zeros(5000, 1)
learning_rate = 0.01
nb_epochs = 1000
minibatch_size = 256

In [6]:
input_dim = x.size(-1)
output_dim = y.size(-1)

model = torch.nn.Sequential(
    nn.Linear(input_dim, 10),
    nn.LeakyReLU(0,1),
    nn.Linear(10,8),
    nn.LeakyReLU(0,1),
    nn.Linear(8,6),
    nn.LeakyReLU(0,1),
    nn.Linear(6, output_dim)
)

loss_function = nn.MSELoss()
oprimizer = torch.optim.Adam(model.parameters()) # Adam은 learning rate 가 필요 없음, SGD는 피룡함
# adam모델을 가장 많이 사용

In [9]:
# 미니배치를 만드는 것
indices = torch.randperm(x.size(0))
print(indices)
x_batch_list = torch.index_select(x, 0, index = indices)
y_batch_list = torch.index_select(y, 0, index = indices)
x_batch_list = x_batch_list.split(minibatch_size, dim=0) # minibatch로 잘려서 [] 에서 [[],[],[]...] 아러한 형태로 바
y_batch_list = y_batch_list.split(minibatch_size, dim=0)
print(len(x_batch_list), len(y_batch_list))

tensor([3608, 1231,  238,  ..., 4539, 1179, 1824])
20 20


In [10]:
for index in range(nb_epochs):
    indices = torch.randperm(x.size(0))

    x_batch_list = torch.index_select(x, 0, index = indices)
    y_batch_list = torch.index_select(y, 0, index = indices)
    x_batch_list = x_batch_list.split(minibatch_size,0)
    y_batch_list = y_batch_list.split(minibatch_size,0)

    for x_minibatch, y_minibatch in zip(x_batch_list, y_batch_list):
        y_minibatch_pred = model(x_minibatch)
        loss = loss_function(y_minibatch_pred, y_minibatch)

        oprimizer.zero_grad()
        loss.backward()
        oprimizer.step()

print(loss)
for param in model.parameters():
    print(param)

tensor(0., grad_fn=<MseLossBackward0>)
Parameter containing:
tensor([[-0.1876,  0.0953,  0.0216, -0.2204,  0.1129,  0.1977,  0.1804, -0.1209,
         -0.3104,  0.2676],
        [-0.2784,  0.1095,  0.2615, -0.1662, -0.2879, -0.1037,  0.2124, -0.2885,
          0.0685, -0.1541],
        [-0.2349, -0.0624, -0.0422, -0.2477,  0.1337,  0.0155, -0.1729, -0.2676,
          0.1140, -0.1250],
        [-0.2975, -0.2216,  0.3099, -0.2528, -0.2747, -0.3051, -0.0590,  0.1243,
          0.0431, -0.0986],
        [ 0.1421, -0.0747, -0.1905, -0.0706,  0.2504, -0.2202, -0.1902, -0.2211,
          0.2742, -0.0883],
        [-0.0356, -0.2966, -0.2881, -0.0213,  0.2192, -0.2798,  0.1919, -0.1688,
         -0.0667,  0.0278],
        [ 0.2715,  0.2532,  0.2579, -0.2067, -0.2403, -0.3376,  0.1507, -0.1608,
         -0.1452,  0.2153],
        [-0.1031,  0.3420,  0.1060,  0.3246, -0.1867,  0.3391, -0.2362, -0.2628,
         -0.0189,  0.2158],
        [ 0.2384, -0.1385,  0.0973,  0.3487,  0.1827, -0.1957,  0.0

In [11]:
# ADAM optimizer 테스트

import torch
import torch.nn as nn

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

x = torch.ones(5000, 10).to(device)
y = torch.zeros(5000, 1).to(device)
learning_rate = 0.01
nb_epochs = 1000
minibatch_size = 256

input_dim = x.size(-1)
output_dim = y.size(-1)

model = torch.nn.Sequential(
    nn.Linear(input_dim, 10),
    nn.LeakyReLU(0,1),
    nn.Linear(10,8),
    nn.LeakyReLU(0,1),
    nn.Linear(8,6),
    nn.LeakyReLU(0,1),
    nn.Linear(6, output_dim)
).to(device)

loss_function = nn.MSELoss()
oprimizer = torch.optim.Adam(model.parameters()) # Adam은 learning rate 가 필요 없음, SGD는 피룡함
# adam모델을 가장 많이 사용

# 미니배치를 만드는 것
indices = torch.randperm(x.size(0), device=device)
print(indices)
x_batch_list = torch.index_select(x, 0, index = indices)
y_batch_list = torch.index_select(y, 0, index = indices)
x_batch_list = x_batch_list.split(minibatch_size, dim=0) # minibatch로 잘려서 [] 에서 [[],[],[]...] 아러한 형태로 바
y_batch_list = y_batch_list.split(minibatch_size, dim=0)
print(len(x_batch_list), len(y_batch_list))

for index in range(nb_epochs):
    indices = torch.randperm(x.size(0), device=device)

    x_batch_list = torch.index_select(x, 0, index = indices)
    y_batch_list = torch.index_select(y, 0, index = indices)
    x_batch_list = x_batch_list.split(minibatch_size,0)
    y_batch_list = y_batch_list.split(minibatch_size,0)

    for x_minibatch, y_minibatch in zip(x_batch_list, y_batch_list):
        y_minibatch_pred = model(x_minibatch)
        loss = loss_function(y_minibatch_pred, y_minibatch)

        oprimizer.zero_grad()
        loss.backward()
        oprimizer.step()

print(loss)
for param in model.parameters():
    print(param)

tensor([2226,  677,  497,  ...,  518,   84, 3923], device='cuda:0')
20 20
tensor(0., device='cuda:0', grad_fn=<MseLossBackward0>)
Parameter containing:
tensor([[ 0.0632, -0.1414,  0.1404, -0.0282,  0.0084,  0.0784,  0.1894,  0.0612,
          0.0196, -0.0827],
        [ 0.2602, -0.0773,  0.1612, -0.1517,  0.2113,  0.1296, -0.0737, -0.3119,
          0.2526, -0.0415],
        [ 0.1612, -0.1563,  0.0577, -0.2659, -0.0224,  0.1242, -0.2874, -0.2807,
         -0.1709,  0.2236],
        [-0.2371, -0.2360,  0.0559,  0.1714, -0.0860, -0.0600, -0.1414,  0.1164,
         -0.0808, -0.1345],
        [-0.1531, -0.0543,  0.2924,  0.2891,  0.0889,  0.1442, -0.1004,  0.1887,
         -0.0801, -0.1334],
        [-0.1101,  0.1824, -0.1669,  0.0430,  0.1436, -0.2186, -0.0727, -0.0910,
         -0.0143, -0.1440],
        [ 0.1189, -0.1547, -0.0036, -0.2904, -0.2642,  0.1655, -0.0483, -0.2525,
         -0.0325,  0.2219],
        [-0.0918,  0.2279, -0.2246,  0.1607, -0.2447, -0.2739,  0.1632,  0.1900,
    